### PR TITLE
[AWS-TASK-2] - Created second task

### PR DESCRIPTION
**Pull request by Konstantin1996**
**AWS TASK 2**

**What was done?**

Manual configured S3/Cloudfront resources:

_S3 link:_ http://my-duplicate-bucket.s3-website-eu-west-1.amazonaws.com/

_CloudFront link:_  https://d17toaafpx31b8.cloudfront.net/

_Automated configured S3/CloudFront resources link:_ https://d148o21qjvuk93.cloudfront.net/

Please, check and review.

### CODE REVIEW

**Comment by maksumov** [comment]
@Konstantin1996 could you provide link to the automatically created S3 Bucket?

**Comment by maksumov** [comment]
Link to the [manually created CF Distribution](https://my-duplicate-bucket.s3-eu-west-1.amazonaws.com/index.html) doesn't work properly. It doesn't allow me to evaluate how well the work was done manually. Please fix it.

**Comment by maksumov** [comment]
image
Your CF Distribution Link redirects to your S3 bucket. To fix this I suggest replacing the Cloudfront Origin Name from **my-duplicate-bucket.s3.amazonaws.com** to **my-duplicate-bucket.s3-eu-west-1.amazonaws.com**

These links might help to clarify the details: 
- https://docs.aws.amazon.com/AmazonS3/latest/dev/Redirects.html
- https://aws.amazon.com/ru/premiumsupport/knowledge-center/s3-http-307-response/

**Comment by maksumov** [comment]
# Task evaluation

## Common

- [x] There is Pull Request on Student's own repo
- [x] PR description has the links to manually created S3 Bucket & CF Distribution
- [x] PR description has the links to automatically created S3 Bucket & CF Distribution - **FAILED!**

## Manual Deployment Check

### S3 Bucket Check (CF Distribution Link is provided)

- [x] S3 Bucket has been created (S3 link is existent)
- [x] S3 Bucket has been configured properly (S3 link shows 403 Access denied error)

### CloudFront Distribution Link Check

- [x] CloudFront Distribution has been created (CloudFront Distribution link is existent)
- [x] CloudFront Distribution has been configured properly - **FAILED!**
- [x] The app has been uploaded to the bucket and is available through the CloudFront Distribution Link - **FAILED!**

## Automatic Deployment Check

### S3 Bucket Check

- [x] S3 Bucket has been created (S3 link is existent) - **FAILED!**
- [x] S3 Bucket has been configured properly (S3 link shows 403 Access denied error) - **FAILED!**

### CloudFront Distribution Link Check

- [x] CloudFront Distribution has been created (CloudFront Distribution link is existent)
- [x] CloudFront Distribution has been configured properly
- [x] The app has been uploaded to the bucket and is available through the CloudFront Distribution Link

### Code Review

- [x] Serverless-finch and serverless-single-page-app plugins are added and configured
- [x] The app can be built and deployed by running npm script command

Not all tests are successfully passed. Datetime of review (UTC): 2020-10-25T16:40:28Z

**Comment by Konstantin1996** [comment]
@maksumov Thank you for review! Fixed link, now it works!

**Comment by maksumov** [comment]
> CloudFront link: https://my-duplicate-bucket.s3-eu-west-1.amazonaws.com/index.html

It doesn't look like a CloudFront link. I can't check it.

And it's better to add your own comment than edit mine. It became more difficult for me to check what has changed.

**Comment by Konstantin1996** [comment]
> > CloudFront link: https://my-duplicate-bucket.s3-eu-west-1.amazonaws.com/index.html
> 
> It doesn't look like a CloudFront link. I can't check it.
> 
> And it's better to add your own comment than edit mine. It became more difficult for me to check what has changed.

Sorry, something went wrong, now the link in the description is correct. Here it is: https://d17toaafpx31b8.cloudfront.net/

Okey, I do not edit your comments anymore)

**Comment by maksumov** [comment]
image

It seems that your CF Distribution has no access to the S3 bucket.

**Comment by Konstantin1996** [comment]
> image
> 
> It seems that your CF Distribution has no access to the S3 bucket.

After I clear cache I have the same picture. It is strange I do not know how to fix it now.

**Comment by Konstantin1996** [comment]
> image
> 
> It seems that your CF Distribution has no access to the S3 bucket.

First time when I did it all links works. After I deleted and create buckets and cloudfront again it does not work . So, maybe it is somehow connected with it. I think the main point here is that the last link works.

**Comment by Shadowmad** [comment]
As per comments above: 
Manual S3 bucket shows 403. But CloudFront does not show anything, but Access Denied
S3
image

CloudFront
image

Automatic S3 link is missing, that should show 403.

Automatic CloudFront seems to work properly: 
image

**Comment by Shadowmad** [comment]
I only assume that your S3 bucket for automation lives in us-east, as it seems you have no specific configuration in your serverless.yml file. So it seems your automatic deploy works. 
image

But next time please pay attention to task requirements and post all links

Link to S3 (guessed based on serverless.yml) - http://rs-second-application.s3-website-us-east-1.amazonaws.com/

**Review by maksumov — APPROVED** [review]

**Comment by VestryOd** [comment]
> > image
> > It seems that your CF Distribution has no access to the S3 bucket.
> 
> First time when I did it all links works. After I deleted and create buckets and cloudfront again it does not work . So, maybe it is somehow connected with it. I think the main point here is that the last link works.



> > image
> > It seems that your CF Distribution has no access to the S3 bucket.
> 
> After I clear cache I have the same picture. It is strange I do not know how to fix it now.

I have the same error - it was in Discord channel mentioned a couple times. There is [link](https://discord.com/channels/755676888680366081/764078229572288542/769523274349936660)

**Review by Shadowmad — APPROVED** [review]

**Pull request merged**
